### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by christophior** [christophior/DogecoinTicker#3]
Crash reported July 10th at 5:37pm

**App Version**
1.2
**Android Version**
Android 4.4
**Device**
HTC D816e (htc_a5dugl)

**Stack Trace**

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:864)
Caused by: java.lang.NumberFormatException: Invalid double: "٠.٠٠٠٣٥"
at java.lang.StringToReal.invalidReal(StringToReal.java:63)
at java.lang.StringToReal.parseDouble(StringToReal.java:269)
at java.lang.Double.parseDouble(Double.java:295)
at christophior.dogecointicker.app.MainActivity$GetJson.formatPricemBTC(MainActivity.java:386)
at christophior.dogecointicker.app.MainActivity$GetJson.updateExchangePrice(MainActivity.java:315)
at christophior.dogecointicker.app.MainActivity$GetJson.doInBackground(MainActivity.java:340)
at christophior.dogecointicker.app.MainActivity$GetJson.doInBackground(MainActivity.java:301)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

**Comment by cristhianescobar** [comment]
If you can reproduce this bug for me in the emulator perhaps using Genymotion I can work on it!
